
version: "3.9"

services:
  database:
    image: mysql:5.7
    container_name: cspDatabase
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cspPWD
      MYSQL_DATABASE: csp
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  adminer:
    image: adminer
    container_name: cspAdminer
    ports:
      - 8080:8080

  app:
    build: .
    container_name: cspApi
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  db-config:
  db-data: