
version: "3.9"

services:
  database_scp:
    image: mysql
    container_name: scp_database
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=scpPWD
      - MYSQL_DATABASE=scp

  adminer:
    image: adminer
    container_name: scp_adminer
    ports:
      - 8080:8080

  app:
    build: .
    container_name: scp_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_scp
    depends_on:
      - database_scp
